### PR TITLE
Strain Gauge Interface v1.0

### PR DESCRIPTION
**Pull request by aaronbeekay**
Work towards v1.0 of the board for manufacturing.

### CODE REVIEW

**Comment by aaronbeekay** [comment]
@arnez1234 - We've been doing design feedback in pull requests like this one, and it seems to be working well, so I'll give notes here. As you add work and commit it to your repository, it will show up here. When you've made all the updates that are needed we'll merge it back into the main BuckeyeCurrent repository.

**Comment by aaronbeekay** [comment]
**Important: there are a lot of consistency errors between the .sch and .brd files in your repository right now (one of them is out of date). Could you have forgotten to commit the latest .sch file you worked on?**
Check your SourceTree - if you have an "Uncommitted changes" section with the .sch file listed, or if you have a red badge on your "Push" button, you should commit and push. EAGLE is completely intolerant of these files being out of sync, so you should look into this before doing other work.

## PCB layout
The board looks great overall, an excellent first design.

* It looks like you intend for the board to be 32mm x 32mm, but the wires on your Dimension layer (which is how the board will be cut) make a 54x38mm board. You should move them in to match where you want your board to be cut.
* You have a few DRC errors that will need to be resolved. You can check them by typing "drc" in the board editor. Make sure you're using the "OSH Park 2-layer" design ruleset - you can select it by clicking "Load" in the DRC window, then navigating to Component-libraries/dru/OSH Park 2-layer.dru.
  * Mostly these errors have to do with you putting a via just barely too close to a trace. You can post here/Slack for help resolving them, or you can catch Victor in person tomorrow.
* The board doesn't have any mounting holes - have you discussed with Victor how the board will be mounted?
* Eventually you will need to add silkscreen (printed text) with stuff like labels for connectors, board name + version, etc

## Schematic
No feedback yet because you might have forgotten to commit the .sch file

## Design standards
* Eventually you will need to make documentation (bill of materials, PDFs of board/schematic, CAM files, etc)

**Comment by arnez1234** [comment]
Hello Aaron,


An update on the strain gauge:


The drc no longer finds errors in the board. Most of the errors were based on via clearances and resistor clearances. The were fixed or approved. I had a huge misunderstanding about the silk screen. The board was implicated based on the thought that the while outlines of the components were walls that the red wires could not go through which made my task twice as hard, but still achievable. Some wires were also rerouted after this explanation from Victor. The overall board size was reduced. Also the circuit schematic has now been pushed. At the moment I am currently working on the silkscreen naming and mounting holes. Lastly the 6 pin micro fit was replaced with another 6 pin through hole micro fit that took less space but relatively similar in respect to the mounting holes.


Cheers!

Arnez



________________________________

**Comment by aaronbeekay** [comment]
@arnez1234 Good stuff - the updated schematic fixed the consistency errors.

Push your work whenever and ping me here, and I'll look it over again.

**Comment by arnez1234** [comment]
@aaronbeekay hey! Strain gauge is ready for review.

**Comment by aaronbeekay** [comment]
@arnez1234 In your schematic, you have the op-amp powered from +5V. The op-amp you're using (TLV2764) can't run off +5V - its supply voltage is 3.6V max (see [datasheet](http://www.ti.com/lit/ds/symlink/tlv2764.pdf)).

I don't know if you picked that or if @Victorb101 did -- it might be possible to just run the thing off +3.3V instead? Thoughts, either of you?

Otherwise looks great.

**Comment by Victorb101** [comment]
@aaronbeekay @arnez1234 We actually have already made the MCN breakouts to route 5V to this sensor.  We could hack it up, but it would be easier to use a 5V chip.  I believe Arnez and I had found one the other day, not sure if this got saved anywhere.

**Comment by aaronbeekay** [comment]
@Victorb101 - It would be convenient to use the TLV2764, we have a bunch of them in stock... how hard would it be to hack on the breakout? Alternatively, maybe this board could have a 3.3V LDO added?

**Comment by aaronbeekay** [comment]
@arnez1234 It sounds like the decision was made to use a different op-amp on your board (some 5V-capable version?)

If that's correct, can you update your BOM to reflect the correct op-amp? Then I can merge this and we can get the thing made.

**Pull request merged**
